### ISSUE TITLE
Undefined index fail_retries

### ISSUE THREAD

**Issue by vzeman** [QualityUnit/php-resqueue-serial#5]
Undefined index: fail_retries in /opt/qu/php-resque-releases/php-resque-3.3.2/lib/Resque/Config/GlobalConfig.php on line 81

Each day we have about 200 notices at 5:00

**Comment by ghost** [comment]
It's when resqu instances are reloaded to rotate logs. Just misconfiguration. We use default value anyway so it's not critical.

Should be set to 3 in config in cloud.

**Comment by ghost** [comment]
config files fixed
